### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by EvoSems** [chrisc123/jebao_aqua-homeassistant#12]
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/jebao_aqua/switch.py:36
integration: Jebao Aqua Aquarium Pump (documentation)
First occurred: 16:02:05 (15 occurrences)
Last logged: 16:02:33

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 453, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 533, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1011, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1670, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/jebao_aqua/switch.py", line 36, in is_on
    return device_data.get('attr', {}).get(self._attribute['name'], False)
           ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by EvoSems** [comment]
Hi Guys. getting the above error running 2 wave makers in master/slave

**Comment by EvoSems** [comment]
I can get the switch to work on/off but the status of the switch isnt being handled. in master/slave I can turn off/on both wave makers with just the one "master" switch. pretty cool

**Comment by chrisc123** [comment]
This crash was in the old polling coordinator, which no longer exists — [v0.4.1-beta](https://github.com/chrisc123/jebao_aqua-homeassistant/releases/tag/v0.4.1-beta) uses a new push-based architecture. Closing as superseded; reopen if anything similar appears on the beta.

**To install the beta:** HACS → Jebao Aqua → ⋮ → Redownload → enable "Show beta versions" → v0.4.1-beta → restart HA.
